version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./build/start_project.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - bundle:/app/vendor/bundle
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=rapidticket
      - POSTGRES_PASSWORD=XEsSBz25n7Upq8nT
  db:
    image: postgres:13.3
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=rapidticket
      - POSTGRES_PASSWORD=XEsSBz25n7Upq8nT
volumes:
  postgres:
  bundle:
